### ISSUE TITLE
Question: How to clear (delete) all the cached data?

### ISSUE THREAD

**Issue by Cedriking** [tcs-de/nodecache#50]
Hello everyone, hope you are all doing good.
I have an app that is using node-cache to cache some json data, the keys are all unique, because i set them with the name of what the user has entered in an input, I have tried cache.flushAll() but it doesnt clear the cache, and for now all I can do is restart the node server to clear it, is there a way to do some kind of cache.del() without sending what to exactly delete and so it can delete everything?

Here is a demo of what I have:
```javascript
var nc = require("node-cache");
var cache = new nc( { stdTTL: 3000 } );

// this cache-key is normally set by what the user add in a field. This is just for example:
var cacheKey = 'key-' + new Date().getTime();

cache.set(cacheKey, { hello: 'world' });
```

Then in another file I have:
```javascript
var nc = require("node-cache");
cache = new nc();
cache.flushAll();
```

Thank you.

**Comment by mpneuried** [comment]
Hi,
you are setting data to node-cache in one file and in the "another file" you want to flush the data from the first file?
That is not possible, because everytime you creating a cache with `new nc();`  its a totally new instance.
You have to use the same instance for both files.

---

Here's a simple solution:

**cache.js:**
```js
var nc = require( "node-cache" );
module.exports = new nc( { stdTTL: 3000 } );
```
> Create a single instance of you cache and export it

**demo.js:**
```javascript
// get the cache instance
var cache = require("./cache");

// this cache-key is normally set by what the user add in a field. This is just for example:
var cacheKey = 'key-' + new Date().getTime();

cache.set(cacheKey, { hello: 'world' });
```

**another-file.js:**
 ```javascript
// get the cache instance
var cache = require("./cache");
cache.flushAll();
```

--- 

Please let me know if i understood your problem and if the solution works for you.

**Comment by Cedriking** [comment]
Thank you, I've set the flushAll in the firstFile.js and it's working now.
