### ISSUE TITLE
why is checkperiod set to 600 by default?

### ISSUE THREAD

**Issue by cuongluu8** [tcs-de/nodecache#52]
Just wondering why zero isn't the default, since by default if the cached value is expired it returns undefined anyway.
Is it used to stop the cache from filling up with expired values?  I would expect an expired value to be removed from the cache on the 'get' call - or is this not the case?

**Comment by mpneuried** [comment]
Hi,
expired values are internally removed on a `.get()` and after every `checkperiod`.

It's set to default 600 to remove deprecated keys from the cache every 10 Minutes.
Otherwise unused keys (never called with `.get()`) would stay within the node-cache instance forever.

So the default `600` will prevent you from a possible memory leak if you use it in the simplest way `new NodeCache();`

**Comment by cuongluu8** [comment]
Ok good to know.
From my point of view, if I add a value to cache then I am responsible for removing it.  It's nice there's an mechanism to automatically remove expired values but I would of expected this to be off by default and turned on as and when required.
No big deal either way though.
Thanks for your quick response.
